### CREATE TRANSACTION
POST http://localhost:8080/transactions
Content-Type: application/json
Accept: application/json

{
    "product_name" : "Kunci Lab. Bahasa",
    "product_type" : "KEY",
    "start_time" : "2025-10-11T10:00:00",
    "end_time" : "2025-10-11T12:00:00",
    "approval_pic" : "Dosen"
 }

### get all transactions
GET http://localhost:8080/transactions
Accept: application/json

### get transaction by id
GET http://localhost:8080/transactions/1
Accept: application/json
